version: '3'

services:
  mongo-bossabox:
    image: mongo
    container_name: mongo-bossabox
    restart: always
    ports:
      - "27017:27017"

  backend-bossabox:
    container_name: bossabox-challenge
    build: .
    command: bash -c "yarn && yarn dev"
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/app
    network_mode: host

